# Git: DylanGore-FYP
- name: configure_ssh
  src: https://github.com/DylanGore-FYP/ansible-role-configure-ssh.git
  version: v1.0.0

# Ansible Galaxy: geerlingguy
- name: geerlingguy.docker
- name: geerlingguy.docker_arm

# Ansible Galaxy: cloudalchemy
- name: cloudalchemy.node_exporter
