version: '3.8'
services:
  # InfluxDB
  influxdb:
    container_name: 'influxdb_{{ host_id }}'
    image: influxdb:2.0.4-alpine
    security_opt:
      - no-new-privileges:true
    networks:
      ingest:
        ipv4_address: 172.16.1.202
    ports:
      - 8086:8086
    environment:
      INFLUXD_REPORTING_DISABLED: 'true'
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: '{{ influx_username }}'
      DOCKER_INFLUXDB_INIT_PASSWORD: '{{ influx_password }}'
      DOCKER_INFLUXDB_INIT_ORG: '{{ influx_org }}'
      DOCKER_INFLUXDB_INIT_BUCKET: '{{ influx_bucket }}'
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: '{{ hostvars['docker_swarm_01']['influx_admin_token'].stdout }}'
      V1_DB_NAME: '{{ influx_bucket }}'
      V1_RP_NAME: '{{ influx_username }}'
      V1_AUTH_USERNAME: '{{ influx_username }}'
      V1_AUTH_PASSWORD: '{{ influx_password }}'
    volumes:
      - /opt/influxdb/scripts:/docker-entrypoint-initdb.d
      - /opt/influxdb/data:/var/lib/influxdb2
      - /opt/influxdb/backups:/backups
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  # Mosquitto
  mosquitto:
    container_name: 'mqtt_{{ host_id }}'
    image: eclipse-mosquitto:openssl
    security_opt:
      - no-new-privileges:true
    networks:
      ingest:
        ipv4_address: 172.16.1.201
    ports:
      - 1883:1883
    volumes:
      - /opt/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /opt/mosquitto/data:/mosquitto/data
      - /opt/mosquitto/passwd:/mosquitto/passwd
      - /opt/shared:/shared

  #  telegraf - InfluxDB Importer
  telegraf:
    container_name: 'telegraf_{{ host_id }}'
    image: telegraf:1.17-alpine
    restart: unless-stopped
    networks:
      ingest:
          ipv4_address: 172.16.1.203
    security_opt:
      - no-new-privileges:true
    volumes:
      # - /opt/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - 'traefik.enable=false'

networks:
  ingest:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.1.0/24
